export const FETCH_GROUPS_SUCCESS = "FETCH_GROUPS_SUCCESS";
export const FETCH_GROUPS_PENDING = "FETCH_GROUPS_PENDING";
export const FETCH_GROUPS_ERROR = "FETCH_GROUPS_ERROR";

export const FETCH_USER_GROUPS_SUCCESS = "FETCH_USER_GROUPS_SUCCESS";
export const FETCH_USER_GROUPS_PENDING = "FETCH_USER_GROUPS_PENDING";
export const FETCH_USER_GROUPS_ERROR = "FETCH_USER_GROUPS_ERROR";

export const DELETE_GROUPS_SUCCESS = "DELETE_GROUPS_SUCCESS";
export const DELETE_GROUPS_PENDING = "DELETE_GROUPS_PENDING";
export const DELETE_GROUPS_ERROR = "DELETE_GROUPS_ERROR";
